### ISSUE TITLE
check if user's email in localStorage

### ISSUE THREAD

**Issue by reemaRahhal** [Fullstack-Alfanar/team-work2#10]
Check if the user exists in localStorage should return true , else retuen false
https://github.com/Fullstack-Alfanar/team-work2/blob/15fa3a6b725f1eee388e115e06e6c10ecad9e901/js/signup.js#L164

**Comment by FidaKhoury** [comment]
hello ,
I dont think you understood why we did this.
it checks if user already exist , because if it already exist then we can not create the a new account with taken email address.
thank you

**Comment by FidaKhoury** [comment]
fixed

**Comment by yosef406** [comment]
this issue is outdated so I'm closing it
