### ISSUE TITLE
check useName

### ISSUE THREAD

**Issue by reemaRahhal** [Fullstack-Alfanar/team-work2#11]
Here in the test I prefer to do each test separately in order to display a message accordingly which will help the user to know what is required in addition the first test should be a test if the value is null then check if it is valid
https://github.com/Fullstack-Alfanar/team-work2/blob/15fa3a6b725f1eee388e115e06e6c10ecad9e901/js/signup.js#L21

**Comment by FidaKhoury** [comment]
hello, 
After we discussed it between us we think it is better to keep it that way, but we are going to change the error message to be more clear what a valid username could be.
thank you

**Comment by FidaKhoury** [comment]
fixed
