### ISSUE TITLE
hey team 3 . i didn't understand why you use span tag  ? you can to Explain ?

### ISSUE THREAD

**Issue by nevensh** [Fullstack-Alfanar/team-work2#11]
https://github.com/Fullstack-Alfanar/team-work2/blob/1d40f8cd71f76a7787b8475197e2b87a228e5d7e/Pages%20Files/homepage.html#L16

**Comment by tyseerhen** [comment]
hey @nevensh i used span tag because of the animation of the css to create an animation board around the bottun ,every span tag means one line around the bottun there are 4 span tags thats mean 4 lines around the bottun to create an animation line ,you can check the code and run it

**Comment by nevensh** [comment]
hey tyseer 
Now I understand .
Full answer .
