### ISSUE TITLE
hello team 3 ->> You can upload all the code. You're missing a submit button for example !!

### ISSUE THREAD

**Issue by RawadGh** [Fullstack-Alfanar/team-work2#13]
https://github.com/Fullstack-Alfanar/team-work2/blob/1d40f8cd71f76a7787b8475197e2b87a228e5d7e/Pages%20Files/signup.html#L91

**Comment by aimanzi** [comment]
hi 
we uplode corrcte file

**Comment by aimanzi** [comment]
problem solved

**Comment by ameer1004** [comment]
Hi Rawad 
there is a submit button in the html file with the name signup. 
please check it and you can try it in the browser.
