### ISSUE TITLE
Here in my opinion, isn't necessary to add "sigin" button again, you already put it at the end of the form.

### ISSUE THREAD

**Issue by AmalShalabi** [Fullstack-Alfanar/team-work2#13]
Here in my opinion, isn't necessary to add "sigin" button again, you already had put it at the end of the form.

_Originally posted by @Amal031 in https://github.com/Fullstack-Alfanar/team-work2/pull/8#discussion_r886950969_

**Comment by HosenNaser** [comment]
the issue has been fixed

**Comment by AmalShalabi** [comment]
great , keep up the good work guys !
