### ISSUE TITLE
You forgot to match  id attribute  to specify this element... I already downloaded the code and it doesn't give me the option to click on the button.(isn't linked with Javascript file) please fix it!

### ISSUE THREAD

**Issue by AmalShalabi** [Fullstack-Alfanar/team-work2#14]
You forgot to match  id attribute  to specify this element... it doesn't give the option to click on the button.(isn't linked with Javascript file) please fix it!

Amal

_Originally posted by @Amal031 in https://github.com/Fullstack-Alfanar/team-work2/pull/8#discussion_r886945528_

**Comment by HosenNaser** [comment]
the issue has been fixed
