### ISSUE TITLE
Here is not obvious to me what is the page about.

### ISSUE THREAD

**Issue by AmalShalabi** [Fullstack-Alfanar/team-work2#15]
Here is not obvious to me what is the page about.
add title or "reset my password" instead of submit button

_Originally posted by @Amal031 in https://github.com/Fullstack-Alfanar/team-work2/pull/8#discussion_r886982044_

**Comment by HosenNaser** [comment]
This page has been deleted

**Comment by AmalShalabi** [comment]
Great ! I see That you've updated the button to "Reset Password" ..
