### ISSUE TITLE
when I roll the mouse  over the button, same text in the button appears under ,is that in purpose? 

### ISSUE THREAD

**Issue by nareens** [Fullstack-Alfanar/team-work2#17]
https://github.com/Fullstack-Alfanar/team-work2/blob/1d40f8cd71f76a7787b8475197e2b87a228e5d7e/Css%20files/homepage.css#L70

**Comment by nareens** [comment]
![nth-child](https://user-images.githubusercontent.com/101823359/170718003-c2a881d0-92bf-47d1-9ed1-b9b706851d36.jpg)

**Comment by ameer1004** [comment]
Hi nareen 
this is like animation for making buttons more beautiful. in other words to make the page more attractive using css style.

**Comment by nareens** [comment]
thank you Ameer for explaining
