### ISSUE TITLE
better in css

### ISSUE THREAD

**Issue by yosef406** [Fullstack-Alfanar/team-work2#21]
https://github.com/Fullstack-Alfanar/team-work2/blob/b253d4e8fec0f3d938baf188c709dd5a3e846695/js/forgotPassword.js#L3

the js file is the last thing to be loaded that is why the elements that are supposed to be hidden are shown at the start of the page 
and then hidden,
it will be better if you use css/scss to hide it and show it.

**Comment by HosenNaser** [comment]
fixed
