### ISSUE TITLE
Please add the cursor property on buttons

### ISSUE THREAD

**Issue by AmalShalabi** [Fullstack-Alfanar/team-work2#22]
In dashbord, in signup page and in forgot your password page:
please add the cursor property to specifie the mouse cursor to be displayed when pointing over the element

_Originally posted by @Amal031 in https://github.com/Fullstack-Alfanar/team-work2/pull/18#discussion_r889495673_

**Comment by HosenNaser** [comment]
This is not a button to change the pointer mouse cursor is best used for buttons nothing else
