### ISSUE TITLE
hey team 3 .  why the " sign in " didn't belong to any tag ? 

### ISSUE THREAD

**Issue by nevensh** [Fullstack-Alfanar/team-work2#23]
https://github.com/Fullstack-Alfanar/team-work2/blob/fe5d7e983011ece5f18fc806c17fafaa529654fb/Pages%20Files/mainpage.html#L22

**Comment by tyseerhen** [comment]
Hey @nevensh as i know if i have a button i dont have to put the “sign up” to any tag please check my answer

**Comment by nevensh** [comment]
hey @tyseerhen 
oki
