### ISSUE TITLE
clarification about getData() function

### ISSUE THREAD

**Issue by reemaRahhal** [Fullstack-Alfanar/team-work2#25]
It's not clear to me what you mean when you keep all the data  in localStorage  inside an array on the dashboard page

_Originally posted by @reemaRahhal in https://github.com/Fullstack-Alfanar/team-work2/pull/18#discussion_r889500741_

**Comment by HosenNaser** [comment]
the cookies saves the email address of the user so, I did this to get the username of the person who logged in with his email, too show it next to the logout button...

**Comment by HosenNaser** [comment]
changed to save only one user
