### ISSUE TITLE
Un professional way 

### ISSUE THREAD

**Issue by nevensh** [Fullstack-Alfanar/team-work2#34]
https://github.com/Fullstack-Alfanar/team-work2/blob/ddfd3cdd55d272f9a1bc3b32a78edb99c7eb644f/Pages%20Files/forgetpassword.html#L24

hey team 3.
why you use br tag ? in return you can use div
every label or every input be inside " div " .
the best way to do a line break .

**Comment by aimanzi** [comment]
solved please check pulles requests

**Comment by nevensh** [comment]
thank you aiman .
good work . continue ...
