### ISSUE TITLE
Correct the spelling of a word " enjoy "

### ISSUE THREAD

**Issue by nevensh** [Fullstack-Alfanar/team-work2#35]
https://github.com/Fullstack-Alfanar/team-work2/blob/d5c6c8ca7590ad514a7117b0e528580418918984/Pages%20Files/wellcom.html#L22

**Comment by aimanzi** [comment]
done **enjoy** and **team** also was written wrong

**Comment by nevensh** [comment]
please fix it

**Comment by aimanzi** [comment]
it fixed

**Comment by nevensh** [comment]
good work
