### ISSUE TITLE
hi team 3, did  you check that the buttons move the page on clicking, to the linked pages in the form ?

### ISSUE THREAD

**Issue by nareens** [Fullstack-Alfanar/team-work2#37]
https://github.com/Fullstack-Alfanar/team-work2/blob/c9d30e29dec9c9d09073303d054c7ab733f2ad48/Pages%20Files/signin.html#L44

**Comment by ameer1004** [comment]
Hi nareen 
we are working on it, just wait for a new push.

**Comment by aimanzi** [comment]
yes i checked  its and its moving but becouse the wellcome page and the forgetpassword page are not mearged yet
