### ISSUE TITLE
I am thinking of using a password type field because when a user types in the password will appear in dots  (more safety)  and not the characters of the password which user enters

### ISSUE THREAD

**Issue by reemaRahhal** [Fullstack-Alfanar/team-work2#5]
I am thinking of using a password type field because when a user types in the password will appear in dots  (more safety)  and not the characters of the password which user enters

_Originally posted by @reemaRahhal in https://github.com/Fullstack-Alfanar/team-work2/pull/2#discussion_r885696987_

**Comment by HosenNaser** [comment]
fixed

**Comment by yosef406** [comment]
this issue has been resolved so i am closing it
