### ISSUE TITLE
hey team 3 . you can Explain to me what the line is meaning ? 

### ISSUE THREAD

**Issue by nevensh** [Fullstack-Alfanar/team-work2#59]
https://github.com/Fullstack-Alfanar/team-work2/blob/2b7a51daeb2a3097cb2c8a5f645187521dac820b/javascript/signInScript.js#L41

**Comment by ameer1004** [comment]
hi 
this line transfer to another page

**Comment by nevensh** [comment]
ok ameer . 
good work
