### ISSUE TITLE
hey team 3 . what the meaning of this line ? 

### ISSUE THREAD

**Issue by nevensh** [Fullstack-Alfanar/team-work2#61]
https://github.com/Fullstack-Alfanar/team-work2/blob/2b7a51daeb2a3097cb2c8a5f645187521dac820b/javascript/signUpScript.js#L72

**Comment by aimanzi** [comment]
its a REGEX mail validation

**Comment by nevensh** [comment]
yes I know that is a REGEX mail validation . 
but I want to know What do these symbols mean?

**Comment by tyseerhen** [comment]
hey neven this regex checkes if the email is valid or unvalid

**Comment by aimanzi** [comment]
we need to lear REGEX to explain it , we use it here as a bulit in function it javas
