### ISSUE TITLE
hey team 3. illogical condition in this line . As Baby in a one year old can't be a user .

### ISSUE THREAD

**Issue by nevensh** [Fullstack-Alfanar/team-work2#62]
https://github.com/Fullstack-Alfanar/team-work2/blob/2b7a51daeb2a3097cb2c8a5f645187521dac820b/javascript/signUpScript.js#L82

**Comment by aimanzi** [comment]
hhhhh i agree whith you but its still a logical number ,

**Comment by nevensh** [comment]
What is required is to build something very close to reality .
please try .

**Comment by aimanzi** [comment]
its only need to change from 0 to a logical age

**Comment by aimanzi** [comment]
age is updated to 12 instead of 0

**Comment by nevensh** [comment]
good work
