### ISSUE TITLE
using function

### ISSUE THREAD

**Issue by nareens** [Fullstack-Alfanar/team-work2#64]
hi team 3, 
in the signupscript.js ' you build a function called checkPassMail() but i couldn't see were it has been used,
can you explain.

**Comment by aimanzi** [comment]
ultimatlely we didnt use it i will delet it thank you for you attention

**Comment by nareens** [comment]
Good work 👍

**Comment by aimanzi** [comment]
Thank you
We update all the changes and we are waiting to you check and merge

Sent from my iPhone

On 29 May 2022, at 22:07, nareen sabihe ***@***.***> wrote:

﻿

Good work 👍
