### ISSUE TITLE
linked pages

### ISSUE THREAD

**Issue by nareens** [Fullstack-Alfanar/team-work2#66]
in the signupscript.js, from were these tow element coming from;
let mailInput = document.getElementById("mailInput");
let passwordInput = document.getElementById("passwordInput");
is the signup script.js link linked to more page otherwise signup.html?

**Comment by tyseerhen** [comment]
hey nareen yes every script linked to html files but the html files were merged to homepage you can check there @nareens

**Comment by aimanzi** [comment]
this two elements :
let mailInput = document.getElementById("mailInput");
let passwordInput = document.getElementById("passwordInput");
is liked to the signin page to receive the data from the mail and the password input and check it with the save data in the local storage

**Comment by nareens** [comment]
Good work 👍
