### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by AmalShalabi** [Fullstack-Alfanar/team-work2#7]
Hey guys ,
I suggest to be more specific , to provide more details . Sign V just for what is already done or you can add percent/notes to explain each step exactly.
One more thing : here you have what we call  "skeleton design" not really webpage. please use the right terms!
Amal

**Comment by FidaKhoury** [comment]
Hey,
Thank you for your suggestion this todo list only for us , to remind us the flow for our project therefore we can write whatever terms we want to remind us, Nothing for you to worry about .
Have a wonderful night 👍🏻

**Comment by yosef406** [comment]
makes since 
i will close this issue
