### ISSUE TITLE
function check Email Validation

### ISSUE THREAD

**Issue by reemaRahhal** [Fullstack-Alfanar/team-work2#9]
Hi, 
The function you built to check the validation of email is very long I think you can perform the test in fewer lines of code
https://github.com/Fullstack-Alfanar/team-work2/blob/15fa3a6b725f1eee388e115e06e6c10ecad9e901/js/signup.js#L32

**Comment by FidaKhoury** [comment]
hello,
you are right working on if possible i will fix it 
thank you

**Comment by FidaKhoury** [comment]
fixed

**Comment by yosef406** [comment]
this issue is outdated so i'm closing it
